# prometheus.yml
global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: 'flask-app'
    # This target matches the service name 'webapp' and port '5000'
    # defined in your docker-compose.yml file.
    static_configs:
      - targets: ['webapp:5000']